import type { Agent } from "./types"

export const mockAgents: Agent[] = [
  // Marketing Agents - Content Creation
  {
    id: "blog-writer",
    name: "Blog Writer Pro",
    description: "AI-powered blog content creation with SEO optimization and brand voice consistency",
    category: "Content Creation",
    section: "marketing",
    capabilities: ["Long-form content", "SEO optimization", "Brand voice matching", "Research integration"],
    pricing_model: "subscription",
    pricing_tier: "starter",
    is_featured: true,
    icon: "✍️",
    votes: 0,
  },
  {
    id: "social-media-manager",
    name: "Social Media Manager",
    description: "Multi-platform social media content creation and scheduling with engagement optimization",
    category: "Social Media",
    section: "marketing",
    capabilities: ["Multi-platform posting", "Content calendar", "Hashtag optimization", "Engagement tracking"],
    pricing_model: "subscription",
    pricing_tier: "professional",
    is_featured: true,
    icon: "📱",
    votes: 0,
  },
  {
    id: "email-copywriter",
    name: "Email Copywriter",
    description: "Conversion-focused email campaigns with A/B testing and personalization",
    category: "Email Marketing",
    section: "marketing",
    capabilities: ["Campaign creation", "A/B testing", "Personalization", "Subject line optimization"],
    pricing_model: "subscription",
    pricing_tier: "professional",
    is_featured: false,
    icon: "📧",
    votes: 0,
  },
  {
    id: "video-script-writer",
    name: "Video Script Writer",
    description: "Engaging video scripts for YouTube, TikTok, and marketing videos",
    category: "Content Creation",
    section: "marketing",
    capabilities: ["Script writing", "Hook creation", "CTA optimization", "Platform-specific formats"],
    pricing_model: "subscription",
    pricing_tier: "starter",
    is_featured: false,
    icon: "🎬",
    votes: 0,
  },

  // Marketing Agents - Advertising & Campaign
  {
    id: "ad-campaign-manager",
    name: "Ad Campaign Manager",
    description: "End-to-end ad campaign management across multiple platforms with budget optimization",
    category: "Advertising",
    section: "marketing",
    capabilities: ["Multi-platform campaigns", "Budget optimization", "Audience targeting", "Performance tracking"],
    pricing_model: "project",
    is_featured: true,
    icon: "🎯",
    votes: 0,
  },
  {
    id: "google-ads-specialist",
    name: "Google Ads Specialist",
    description: "Expert Google Ads management with keyword research and bid optimization",
    category: "Advertising",
    section: "marketing",
    capabilities: ["Keyword research", "Bid management", "Quality score optimization", "Conversion tracking"],
    pricing_model: "retainer",
    is_featured: false,
    icon: "🔍",
    votes: 0,
  },
  {
    id: "landing-page-optimizer",
    name: "Landing Page Optimizer",
    description: "Conversion-focused landing page creation and optimization",
    category: "Advertising",
    section: "marketing",
    capabilities: ["Page design", "A/B testing", "Conversion optimization", "Mobile optimization"],
    pricing_model: "project",
    is_featured: false,
    icon: "🚀",
    votes: 0,
  },
  {
    id: "creative-brief-generator",
    name: "Creative Brief Generator",
    description: "Comprehensive creative briefs for campaigns and content projects",
    category: "Brand Management",
    section: "marketing",
    capabilities: ["Brief creation", "Stakeholder alignment", "Creative direction", "Brand guidelines"],
    pricing_model: "addon",
    is_featured: false,
    icon: "📋",
    votes: 0,
  },

  // Marketing Agents - Analytics & Research
  {
    id: "analytics-reporter",
    name: "Analytics Reporter",
    description: "Automated marketing analytics reports with actionable insights",
    category: "Analytics",
    section: "marketing",
    capabilities: ["Data analysis", "Report generation", "Trend identification", "Recommendations"],
    pricing_model: "subscription",
    pricing_tier: "professional",
    is_featured: true,
    icon: "📊",
    votes: 0,
  },
  {
    id: "competitor-research",
    name: "Competitor Research Analyst",
    description: "Deep competitive analysis and market intelligence",
    category: "Research",
    section: "marketing",
    capabilities: ["Competitor tracking", "Market analysis", "SWOT analysis", "Opportunity identification"],
    pricing_model: "project",
    is_featured: false,
    icon: "🔬",
    votes: 0,
  },
  {
    id: "audience-insights",
    name: "Audience Insights Engine",
    description: "Customer behavior analysis and audience segmentation",
    category: "Analytics",
    section: "marketing",
    capabilities: ["Behavior analysis", "Segmentation", "Persona creation", "Journey mapping"],
    pricing_model: "subscription",
    pricing_tier: "enterprise",
    is_featured: false,
    icon: "👥",
    votes: 0,
  },
  {
    id: "performance-optimizer",
    name: "Performance Optimizer",
    description: "Real-time campaign optimization and performance enhancement",
    category: "Analytics",
    section: "marketing",
    capabilities: ["Real-time optimization", "Performance tracking", "Budget allocation", "ROI analysis"],
    pricing_model: "retainer",
    is_featured: false,
    icon: "⚡",
    votes: 0,
  },

  // Marketing Agents - SEO & Technical
  {
    id: "seo-optimizer",
    name: "SEO Optimizer",
    description: "Comprehensive SEO strategy and implementation",
    category: "SEO",
    section: "marketing",
    capabilities: ["Keyword research", "On-page SEO", "Technical SEO", "Link building"],
    pricing_model: "subscription",
    pricing_tier: "professional",
    is_featured: true,
    icon: "🔎",
    votes: 0,
  },
  {
    id: "content-strategist",
    name: "Content Strategist",
    description: "Strategic content planning and editorial calendar management",
    category: "Content Creation",
    section: "marketing",
    capabilities: ["Content strategy", "Editorial calendar", "Topic research", "Content gap analysis"],
    pricing_model: "retainer",
    is_featured: false,
    icon: "📅",
    votes: 0,
  },

  // Technical Agents - Architecture & Development
  {
    id: "solution-architect",
    name: "Solution Architect",
    description: "Enterprise-grade system architecture and technical planning",
    category: "Architecture",
    section: "technical",
    capabilities: ["System design", "Architecture planning", "Technology selection", "Scalability planning"],
    pricing_model: "project",
    is_featured: true,
    icon: "🏗️",
    votes: 0,
  },
  {
    id: "fullstack-developer",
    name: "Full-Stack Developer",
    description: "End-to-end application development with modern frameworks",
    category: "Development",
    section: "technical",
    capabilities: ["Frontend development", "Backend development", "API design", "Database design"],
    pricing_model: "project",
    is_featured: true,
    icon: "💻",
    votes: 0,
  },
  {
    id: "technical-writer",
    name: "Technical Writer",
    description: "Comprehensive technical documentation and API references",
    category: "Development",
    section: "technical",
    capabilities: ["Documentation", "API references", "User guides", "Code examples"],
    pricing_model: "project",
    is_featured: false,
    icon: "📝",
    votes: 0,
  },
  {
    id: "security-auditor",
    name: "Security Auditor",
    description: "Security assessments and vulnerability analysis",
    category: "Architecture",
    section: "technical",
    capabilities: ["Security audits", "Vulnerability scanning", "Compliance checking", "Remediation planning"],
    pricing_model: "project",
    is_featured: false,
    icon: "🔒",
    votes: 0,
  },
  {
    id: "database-designer",
    name: "Database Designer",
    description: "Optimized database schema design and query optimization",
    category: "Development",
    section: "technical",
    capabilities: ["Schema design", "Query optimization", "Migration planning", "Performance tuning"],
    pricing_model: "project",
    is_featured: false,
    icon: "🗄️",
    votes: 0,
  },
  {
    id: "devops-engineer",
    name: "DevOps Engineer",
    description: "CI/CD pipeline setup and infrastructure automation",
    category: "DevOps",
    section: "technical",
    capabilities: ["CI/CD setup", "Infrastructure as code", "Monitoring", "Deployment automation"],
    pricing_model: "project",
    is_featured: false,
    icon: "⚙️",
    votes: 0,
  },

  // Coming Soon Agents
  {
    id: "influencer-outreach",
    name: "Influencer Outreach Manager",
    description: "Automated influencer discovery and outreach campaigns",
    category: "Social Media",
    section: "coming_soon",
    capabilities: ["Influencer discovery", "Outreach automation", "Campaign tracking", "ROI measurement"],
    pricing_model: "coming_soon",
    is_featured: false,
    icon: "🌟",
    votes: 0,
  },
  {
    id: "podcast-producer",
    name: "Podcast Producer",
    description: "End-to-end podcast production and distribution",
    category: "Content Creation",
    section: "coming_soon",
    capabilities: ["Script writing", "Audio editing", "Distribution", "Show notes"],
    pricing_model: "coming_soon",
    is_featured: false,
    icon: "🎙️",
    votes: 0,
  },
  {
    id: "pr-specialist",
    name: "PR Specialist",
    description: "Media relations and press release distribution",
    category: "Brand Management",
    section: "coming_soon",
    capabilities: ["Press releases", "Media outreach", "Crisis management", "Brand monitoring"],
    pricing_model: "coming_soon",
    is_featured: false,
    icon: "📰",
    votes: 0,
  },
  {
    id: "conversion-rate-optimizer",
    name: "Conversion Rate Optimizer",
    description: "Advanced CRO testing and optimization",
    category: "Analytics",
    section: "coming_soon",
    capabilities: ["A/B testing", "Multivariate testing", "User behavior analysis", "Optimization recommendations"],
    pricing_model: "coming_soon",
    is_featured: false,
    icon: "📈",
    votes: 0,
  },
]
