// Supabase configuration
export const SUPABASE_CONFIG = {
  SUPABASE_URL: process.env.https://jtphpvdlshkfssoqqrpd.supabase.co!,
  NEXT_PUBLIC_SUPABASE_URL: process.env.https://jtphpvdlshkfssoqqrpd.supabase.co!,
  SUPABASE_ANON_KEY: process.env.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0cGhwdmRsc2hrZnNzb3FxcnBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MDE4NDcsImV4cCI6MjA3NDA3Nzg0N30.d8T89xJTWiTFJ5BDQAofpb5o_1AdsNxBlX8udBhKKy4!,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0cGhwdmRsc2hrZnNzb3FxcnBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MDE4NDcsImV4cCI6MjA3NDA3Nzg0N30.d8T89xJTWiTFJ5BDQAofpb5o_1AdsNxBlX8udBhKKy4!,
  SUPABASE_SERVICE_ROLE_KEY: process.env.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0cGhwdmRsc2hrZnNzb3FxcnBkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1ODUwMTg0NywiZXhwIjoyMDc0MDc3ODQ3fQ.-djEXjjpOEap9gC8X3ZZkgAIh5IYM9qKFoznSZaq5R0!,
  SUPABASE_JWT_SECRET: process.env.Ke+7gBUqKR18dKgPBF91y2Xb6MOV+6WC1tm8VH3AxtuVsG8w7w9PDHfYNKu92d3/aledcOB0VfPl8S7cHWWkMw==!,
} as const
